spring.application.name=Aulas
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_aulas
spring.datasource.username=root
spring.datasource.password=UTN2575
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true